### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xavwashere** [xavwashere/YAGDDB#4]
- [ ] Add daily command
- [ ] Add weekly command
- [ ] Add search command
- [ ] Add a command that shows a user's recent level(s?)
